/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dormidospizza;

import java.io.BufferedReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diego
 */
public class Admin extends javax.swing.JInternalFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jCBoxSucursal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFieldPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAreaDescripcion = new javax.swing.JTextArea();
        jButtonCrear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Administración");

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Sucursal: ");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jCBoxSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala", "El Progreso", "Jalapa" }));
        jCBoxSucursal.setToolTipText("");
        jCBoxSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxSucursalActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jCBoxSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 22, 128, -1));

        jLabel2.setText("Pizzas");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("Nombre: ");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jTFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFieldNombreActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 238, -1));

        jLabel4.setText("Precio: ");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jTFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFieldPrecioActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 108, -1));

        jLabel5.setText("Descripción: ");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jTAreaDescripcion.setColumns(20);
        jTAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTAreaDescripcion);

        jDesktopPane1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 452, 76));

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripción", "Precio"
            }
        ));
        jScrollPane2.setViewportView(Tabla);

        jDesktopPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 479, 146));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFieldNombreActionPerformed

    private void jCBoxSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxSucursalActionPerformed

    private void jTFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFieldPrecioActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        String sucursal = (String)jCBoxSucursal.getSelectedItem();
        String nombre = jTFieldNombre.getText();
        String precio = jTFieldPrecio.getText();
        String descripcion = jTAreaDescripcion.getText();
        
        try{
            DefaultTableModel model = (DefaultTableModel)Tabla.getModel();
            model.addRow(new Object[]{nombre,descripcion,precio});
            if(sucursal.contains("Guatemala")){
                FileWriter Writer = new FileWriter("guatemala.txt", true);
                Writer.write(""+nombre+"-"+precio+"-"+descripcion);
                Writer.write(System.getProperty("line.separator"));
                Writer.close();
                new Admin().setVisible(true);
                jTFieldNombre.setText("");
                jTFieldPrecio.setText("");
                jTAreaDescripcion.setText("");
            }
            
            if(sucursal.contains("El Progreso")){
                FileWriter Writer = new FileWriter("progreso.txt", true);
                Writer.write(""+nombre+"-"+precio+"-"+descripcion);
                Writer.write(System.getProperty("line.separator"));
                Writer.close();
                new Admin().setVisible(true);
                jTFieldNombre.setText("");
                jTFieldPrecio.setText("");
                jTAreaDescripcion.setText("");
            }
            
            if(sucursal.contains("Jalapa")){
                FileWriter Writer = new FileWriter("jalapa.txt", true);
                Writer.write(""+nombre+"-"+precio+"-"+descripcion);
                Writer.write(System.getProperty("line.separator"));
                Writer.close();
                new Admin().setVisible(true);
                jTFieldNombre.setText("");
                jTFieldPrecio.setText("");
                jTAreaDescripcion.setText("");
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Error");
        }
        
    }//GEN-LAST:event_jButtonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jCBoxSucursal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAreaDescripcion;
    private javax.swing.JTextField jTFieldNombre;
    private javax.swing.JTextField jTFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
